### ISSUE TITLE
触摸事件兼容

### ISSUE THREAD

**Issue by julian103822** [oasis-engine/polyfill-pointer-event#1]
在ipad上的safari和uc浏览器上触摸没反应

**Comment by cptbtptpbcptdtptp** [comment]
引擎版本需要升级到 0.8 最新，或者直接联系我，给我复现的最小 Demo 我优先帮你解决。

**Comment by julian103822** [comment]
引擎版本升级到 0.8 最新了 还是不行 辛苦帮忙看下这个demo
https://github.com/julian103822/oasis-engine-app

**Comment by cptbtptpbcptdtptp** [comment]
Ipad的版本和 UC 浏览器的版本麻烦提供一下，我已经跑起来你的 Demo 了。

**Comment by julian103822** [comment]
Ipad：12.5.5  UC：3.0.1

**Comment by cptbtptpbcptdtptp** [comment]
麻烦钉钉加一下：anz-j7t4zaz92
或者微信：wsz496974703

**Comment by cptbtptpbcptdtptp** [comment]
请使用最新版本，已修复。
